<Project>
  <PropertyGroup>
    <Authors>mariusmuntean</Authors>
    <RepositoryUrl>https://github.com/mariusmuntean/Simple3D-Maui</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>$(RepositoryUrl)</PackageProjectUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>
</Project>
